name: ci
env:
  OPENAI_API_KEY: "dummy"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"
          enable-cache: true
          activate-environment: true
      - name: Install Reflex
        run: uv pip install -r requirements.txt pyright
      - name: Run Pyright
        run: pyright .

  check-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"
          enable-cache: true
          activate-environment: true
      - name: Install Reflex
        run: uv pip install -r requirements.txt
      - name: Run Ruff
        uses: astral-sh/ruff-action@v3

  check-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"
          enable-cache: true
          activate-environment: true
      - name: Install Reflex
        run: uv pip install -r requirements.txt

      - name: Initialize Reflex
        run: reflex init

      - name: Build frontend
        run: reflex export
